FROM openjdk:17
MAINTAINER lancer lacer1582@gmail.com

RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \&& echo 'Asia/Shanghai' >/etc/timezone

# /tmp 目录作为容器数据卷目录，SpringBoot内嵌Tomcat容器默认使用/tmp作为工作目录，任何向 /tmp 中写入的信息不会记录进容器存储层，从而保证容器存储层的无状态化
# 在宿主机的/var/lib/docker目录下创建一个临时文件并把它链接到容器中的/tmp目录
VOLUME /tmp

# 复制jar到镜像
ADD wing-gateway-1.0.jar gateway.jar

ENTRYPOINT ["java", "-Xmx128m", "-jar", "/gateway.jar"]

EXPOSE 8000
